### ISSUE TITLE
Modernize with #[SensitiveParameter]

### ISSUE THREAD

**Issue by DubbaThony** [furqansiddiqui/bip39-mnemonic-php#3]
Since library is for php 8.1+, without breaking any compatibility, it's likely to be good idea to modernize library with `#[\SensitiveParameter]` tag for sensitive function parameters.

This is php 8.2 feature, but will not break in php 8.1. This php feature masks function parameters in stack traces etc, preventing potential accidental leak of secret such as mnemonic via stack traces / crash messages.

**Comment by furqansiddiqui** [comment]
Completed
